name: build-and-push-task

on:
  push:
    branches: [ "task2" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true  
          tags: ${{ secrets.DOCKER_USERNAME }}/myapp:latest

      - name: Run container (optional)
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/myapp:latest
          docker run -d -p 8080:80 --name myapp ${{ secrets.DOCKER_USERNAME }}/myapp:latest

      - name: push to Docker Hub
        run: |
          docker login -u ${{ secrets.GH_name }} -p ${{ secrets.GH_token }}
          docker push ${{ secrets.DOCKER_USERNAME }}/myapp:latest
