name: Build and Run Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t myapp .

      - name: Run Docker container
        run: docker run -d -p 5000:5000 --name myapp myapp

      - name: Check running containers
        run: docker ps -a
